# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FPGALAB/final_v4/final/final.srcs/sources_1/bd/design_1/ip/design_1_start_signal_0_1/design_1_start_signal_0_1.xci
# IP: The module: 'design_1_start_signal_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGALAB/final_v4/final/final.srcs/sources_1/bd/design_1/ip/design_1_start_signal_0_1/src/start_signal_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_start_signal_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/FPGALAB/final_v4/final/final.srcs/sources_1/bd/design_1/ip/design_1_start_signal_0_1/design_1_start_signal_0_1.xci
# IP: The module: 'design_1_start_signal_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGALAB/final_v4/final/final.srcs/sources_1/bd/design_1/ip/design_1_start_signal_0_1/src/start_signal_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_start_signal_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
