# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adder_pc_0_0/design_1_adder_pc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_adder_pc_0_0 || ORIG_REF_NAME==design_1_adder_pc_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ALU_0_0/design_1_ALU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ALU_0_0 || ORIG_REF_NAME==design_1_ALU_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_imme_ext_0_0/design_1_imme_ext_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_imme_ext_0_0 || ORIG_REF_NAME==design_1_imme_ext_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_jump_pc_0_0/design_1_jump_pc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_jump_pc_0_0 || ORIG_REF_NAME==design_1_jump_pc_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mem_data_0_0/design_1_mem_data_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mem_data_0_0 || ORIG_REF_NAME==design_1_mem_data_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mem_inst_0_0/design_1_mem_inst_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mem_inst_0_0 || ORIG_REF_NAME==design_1_mem_inst_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux_2_8bits_0_0/design_1_mux_2_8bits_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_2_8bits_0_0 || ORIG_REF_NAME==design_1_mux_2_8bits_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux_2_0_0/design_1_mux_2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_2_0_0 || ORIG_REF_NAME==design_1_mux_2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux_4_0_0/design_1_mux_4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_4_0_0 || ORIG_REF_NAME==design_1_mux_4_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_nop_0_0/design_1_nop_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_nop_0_0 || ORIG_REF_NAME==design_1_nop_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg_Control_D_0_0/design_1_reg_Control_D_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_reg_Control_D_0_0 || ORIG_REF_NAME==design_1_reg_Control_D_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg_Control_E_0_0/design_1_reg_Control_E_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_reg_Control_E_0_0 || ORIG_REF_NAME==design_1_reg_Control_E_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg_Control_M_0_0/design_1_reg_Control_M_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_reg_Control_M_0_0 || ORIG_REF_NAME==design_1_reg_Control_M_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg_Control_W_0_0/design_1_reg_Control_W_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_reg_Control_W_0_0 || ORIG_REF_NAME==design_1_reg_Control_W_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg_E_0_0/design_1_reg_E_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_reg_E_0_0 || ORIG_REF_NAME==design_1_reg_E_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg_M_0_0/design_1_reg_M_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_reg_M_0_0 || ORIG_REF_NAME==design_1_reg_M_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg_pc_0_0/design_1_reg_pc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_reg_pc_0_0 || ORIG_REF_NAME==design_1_reg_pc_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg_W_0_0/design_1_reg_W_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_reg_W_0_0 || ORIG_REF_NAME==design_1_reg_W_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_regfile_0_0/design_1_regfile_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_regfile_0_0 || ORIG_REF_NAME==design_1_regfile_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mem_ctrl_0_0/design_1_mem_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mem_ctrl_0_0 || ORIG_REF_NAME==design_1_mem_ctrl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mem_ctrl_1_0/design_1_mem_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mem_ctrl_1_0 || ORIG_REF_NAME==design_1_mem_ctrl_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux_2_1_0/design_1_mux_2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_2_1_0 || ORIG_REF_NAME==design_1_mux_2_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux_2_2_0/design_1_mux_2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_2_2_0 || ORIG_REF_NAME==design_1_mux_2_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux_4_1_0/design_1_mux_4_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_4_1_0 || ORIG_REF_NAME==design_1_mux_4_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux_4_2_0/design_1_mux_4_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_4_2_0 || ORIG_REF_NAME==design_1_mux_4_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux_4_3_0/design_1_mux_4_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_4_3_0 || ORIG_REF_NAME==design_1_mux_4_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mux_2_3_0/design_1_mux_2_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mux_2_3_0 || ORIG_REF_NAME==design_1_mux_2_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_start_signal_0_1/design_1_start_signal_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_start_signal_0_1 || ORIG_REF_NAME==design_1_start_signal_0_1} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
